// Mock data for NearNative — hyperlocal skill-sharing platform

import priyaPhoto from '../assets/teachers/priya.png';
import arjunPhoto from '../assets/teachers/arjun.png';
import meenaPhoto from '../assets/teachers/meena.png';
import raviPhoto from '../assets/teachers/ravi.png';
import sunitaPhoto from '../assets/teachers/sunita.png';
import kabirPhoto from '../assets/teachers/kabir.png';

import photographyImg from '../assets/skills/photography.png';
import cookingImg from '../assets/skills/cooking.png';
import tailoringImg from '../assets/skills/tailoring.png';
import languageImg from '../assets/skills/language.png';
import musicImg from '../assets/skills/music.png';
import wellnessImg from '../assets/skills/wellness.png';
import technologyImg from '../assets/skills/technology.png';
import artcraftImg from '../assets/skills/artcraft.png';

export const mentors = [
  {
    id: 1,
    name: 'Priya Sharma',
    avatar: 'PS',
    avatarColor: '#22C55E',
    photo: priyaPhoto,
    skill: 'Portrait Photography',
    category: 'Photography',
    distance: '0.8 km',
    rating: 4.9,
    reviews: 128,
    vouches: 47,
    pricePerSession: 350,
    currency: '₹',
    verified: true,
    languages: ['Hindi', 'English'],
    bio: 'Award-winning photographer with 8 years of experience teaching beginners and professionals alike.',
    availability: 'Weekends',
    location: 'Koramangala, Bangalore',
    tags: ['DSLR', 'Composition', 'Editing'],
    badges: ['Top Rated', 'Fast Responder'],
  },
  {
    id: 2,
    name: 'Arjun Mehta',
    avatar: 'AM',
    avatarColor: '#3B82F6',
    photo: arjunPhoto,
    skill: 'Biryani Making',
    category: 'Cooking',
    distance: '1.2 km',
    rating: 5.0,
    reviews: 83,
    vouches: 62,
    pricePerSession: 200,
    currency: '₹',
    verified: true,
    languages: ['Hindi', 'Urdu', 'English'],
    bio: 'Third-generation dum biryani chef. Learn the authentic Hyderabadi technique at home.',
    availability: 'Daily',
    location: 'HSR Layout, Bangalore',
    tags: ['Hyderabadi', 'Dum Cooking', 'Spices'],
    badges: ['Community Favourite', 'Super Teacher'],
  },
  {
    id: 3,
    name: 'Meena Krishnan',
    avatar: 'MK',
    avatarColor: '#F59E0B',
    photo: meenaPhoto,
    skill: 'Tailoring & Fashion',
    category: 'Tailoring',
    distance: '0.4 km',
    rating: 4.8,
    reviews: 211,
    vouches: 89,
    pricePerSession: 150,
    currency: '₹',
    verified: true,
    languages: ['Tamil', 'Kannada', 'English'],
    bio: 'Expert in traditional and western tailoring. Teaches pattern-making to Kanjivaram saree draping.',
    availability: 'Mon-Sat',
    location: 'Indiranagar, Bangalore',
    tags: ['Pattern Making', 'Embroidery', 'Alterations'],
    badges: ['Most Vouched', 'Neighbourhood Star'],
  },
  {
    id: 4,
    name: 'Ravi Nair',
    avatar: 'RN',
    avatarColor: '#EC4899',
    photo: raviPhoto,
    skill: 'Spoken English',
    category: 'Language',
    distance: '2.1 km',
    rating: 4.7,
    reviews: 304,
    vouches: 134,
    pricePerSession: 250,
    currency: '₹',
    verified: false,
    languages: ['Malayalam', 'Tamil', 'English', 'Hindi'],
    bio: 'Former corporate trainer helping working professionals gain confidence in business English.',
    availability: 'Evenings',
    location: 'Whitefield, Bangalore',
    tags: ['Business English', 'Pronunciation', 'Interviews'],
    badges: ['Most Reviews'],
  },
  {
    id: 5,
    name: 'Sunita Verma',
    avatar: 'SV',
    avatarColor: '#8B5CF6',
    photo: sunitaPhoto,
    skill: 'Yoga & Meditation',
    category: 'Wellness',
    distance: '0.6 km',
    rating: 4.9,
    reviews: 177,
    vouches: 93,
    pricePerSession: 300,
    currency: '₹',
    verified: true,
    languages: ['Hindi', 'English'],
    bio: 'RYT-200 certified yoga teacher. Specialises in morning Hatha and stress-relief meditation.',
    availability: 'Mornings',
    location: 'Jayanagar, Bangalore',
    tags: ['Hatha Yoga', 'Pranayama', 'Mindfulness'],
    badges: ['Top Rated', 'Early Bird'],
  },
  {
    id: 6,
    name: 'Kabir Ansari',
    avatar: 'KA',
    avatarColor: '#EF4444',
    photo: kabirPhoto,
    skill: 'Guitar & Music Theory',
    category: 'Music',
    distance: '1.9 km',
    rating: 4.8,
    reviews: 95,
    vouches: 51,
    pricePerSession: 400,
    currency: '₹',
    verified: true,
    languages: ['Hindi', 'English'],
    bio: 'Performing musician teaching acoustic, classical and Bollywood guitar for 12 years.',
    availability: 'Flexible',
    location: 'BTM Layout, Bangalore',
    tags: ['Acoustic', 'Classical', 'Bollywood'],
    badges: ['Rising Star', 'Fast Responder'],
  },
];

export const testimonials = [
  {
    id: 1,
    learner: 'Ananya Roy',
    avatar: 'AR',
    avatarColor: '#22C55E',
    skill: 'Photography',
    teacher: 'Priya Sharma',
    quote: 'Priya taught me more in 3 sessions than months of YouTube tutorials. She is patient and incredibly skilled. I already shot my first paid gig!',
    rating: 5,
    date: '2 weeks ago',
    location: 'Koramangala',
  },
  {
    id: 2,
    learner: 'Deepak Iyer',
    avatar: 'DI',
    avatarColor: '#3B82F6',
    skill: 'Biryani Making',
    teacher: 'Arjun Mehta',
    quote: 'The dum biryani recipe was a family secret he graciously shared. My family couldn\'t believe I cooked it. Arjun is a master teacher.',
    rating: 5,
    date: '1 month ago',
    location: 'HSR Layout',
  },
  {
    id: 3,
    learner: 'Fatima Khan',
    avatar: 'FK',
    avatarColor: '#F59E0B',
    skill: 'Spoken English',
    teacher: 'Ravi Nair',
    quote: 'I was terrified of speaking in meetings. After 2 months with Ravi, I presented to 50 people and got a promotion. Life-changing!',
    rating: 5,
    date: '3 weeks ago',
    location: 'Whitefield',
  },
];

export const stats = [
  { label: 'Teachers Onboarded', value: '12,400+', icon: 'Users' },
  { label: 'Community Vouches', value: '89,200+', icon: 'Heart' },
  { label: 'Skills Available', value: '340+', icon: 'BookOpen' },
  { label: 'Sessions Completed', value: '2.1M+', icon: 'CheckCircle' },
];

export const skillCategories = [
  { id: 1, name: 'Photography', icon: 'Camera', count: 234, color: '#3B82F6', bg: '#EFF6FF', image: photographyImg },
  { id: 2, name: 'Cooking', icon: 'ChefHat', count: 412, color: '#F59E0B', bg: '#FFFBEB', image: cookingImg },
  { id: 3, name: 'Tailoring', icon: 'Scissors', count: 187, color: '#EC4899', bg: '#FDF2F8', image: tailoringImg },
  { id: 4, name: 'Language', icon: 'MessageCircle', count: 298, color: '#8B5CF6', bg: '#F5F3FF', image: languageImg },
  { id: 5, name: 'Music', icon: 'Music', count: 156, color: '#EF4444', bg: '#FEF2F2', image: musicImg },
  { id: 6, name: 'Wellness', icon: 'Leaf', count: 203, color: '#22C55E', bg: '#F0FDF4', image: wellnessImg },
  { id: 7, name: 'Technology', icon: 'Code2', count: 321, color: '#06B6D4', bg: '#ECFEFF', image: technologyImg },
  { id: 8, name: 'Art & Craft', icon: 'Palette', count: 178, color: '#F97316', bg: '#FFF7ED', image: artcraftImg },
];

export const exampleSkills = ['Photography', 'Biryani Making', 'Tailoring', 'Spoken English', 'Guitar', 'Yoga'];
